### ISSUE TITLE
ezvis crashes during synchronization

### ISSUE THREAD

**Issue by parmentf** [madec-project/ezvis#2]
Here is the error message:

```
$ node cli data5
Core version : 2.1.3
Configuration : /home/parmentf/dev/castorjs/ezvis/data5.json
Theme : /home/parmentf/dev/castorjs/ezvis
Source : /home/parmentf/dev/castorjs/ezvis/data5
Server is listening on port 3000.

/home/parmentf/dev/castorjs/castor-core/node_modules/castor-load/node_modules/mongodb/lib/mongodb/mongo_client.js:475
          throw err
                ^
TypeError: Cannot call method 'ensureIndex' of undefined
    at /home/parmentf/dev/castorjs/castor-core/node_modules/castor-load/lib/sync.js:70:17
    at Db.collection (/home/parmentf/dev/castorjs/castor-core/node_modules/castor-load/node_modules/mongodb/lib/mongodb/db.js:524:27)
    at func (/home/parmentf/dev/castorjs/castor-core/node_modules/castor-load/lib/sync.js:66:8)
    at /home/parmentf/dev/castorjs/castor-core/node_modules/castor-load/node_modules/mongodb/lib/mongodb/mongo_client.js:472:11
    at process._tickCallback (node.js:419:13)
```

Here is the JSON settings concerning data:

```json
{
  "title": "Films",
  "collectionName": "data5",
  "description": "Several films to demontrate the usage of VISIR",
  "documentFields": {
    "$title": {
      "visible": true,
      "label": "Title",
      "path": "content.json.title"
    },
    "$year": {
      "visible": true,
      "label": "Year",
      "path": "content.json.year"
    },
    "$director": {
      "visible": true,
      "label": "Director",
      "path": "content.json.director"
    },
    "$actors": {
      "label": "Actors",
      "path": "content.json.actors",
      "parseCSV" : "/",
      "foreach": {
        "trim": true
      }
    },
    "$vactors": {
      "label": "Actors",
      "noindex": true,
      "path": "actors",
      "join": ", "
    },
    "$text": {
      "get" : ["title", "year", "director", "actors"],
      "join": "|"
    }
  }
}
```

Maybe it's due to castorjs/castor-core@d5d4a9607998efa3bf7a158e32654722c924acec (as I use castor-core@2.1.3) or castorjs/castor-core@31967a7c3267204a06c79a0123f60a9586a36285.

Extract of castor-core dependencies:
```bash
$ npm ls
castor-core@2.1.3 /home/parmentf/dev/castorjs/castor-core
...
├─┬ castor-load@4.2.0
│ ├── bytes@1.0.0
│ ├─┬ chokidar@0.12.6
│ │ ├── async-each@0.1.6
│ │ └─┬ readdirp@1.3.0
│ │   ├── graceful-fs@2.0.3
│ │   └─┬ readable-stream@1.0.33
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├── clone@0.2.0
│ ├── findit@1.1.1
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├── mkdirp@0.3.5
│ ├─┬ mongodb@1.4.31
│ │ ├─┬ bson@0.2.19
│ │ │ └── nan@1.6.2
│ │ ├─┬ kerberos@0.0.9
│ │ │ └── nan@1.6.2
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├─┬ needle@0.7.11
│ │ └── iconv-lite@0.4.7
│ ├─┬ once@1.3.1
│ │ └── wrappy@1.0.1
│ └─┬ tingodb@0.2.2
│   ├── async@0.9.0
│   ├── lodash@2.4.1
│   └── safe@0.2.1
├─┬ castor-load-csv@2.1.1
│ ├── clone@0.1.19
│ └── csv-string@2.2.5
├─┬ datamodel@1.1.1
│ └─┬ once@1.3.1
│   └── wrappy@1.0.1
├─┬ debug@2.1.1
│ └── ms@0.6.2
├── extend@2.0.0
├── flat@1.5.0
├─┬ formatik@1.2.0
│ └── dateable@1.0.1
├── heartbeats@1.1.1
├─┬ jbj@3.2.0
│ ├── csv-string@2.2.5
│ ├── filtrex@0.5.4
│ ├── json-mask@0.3.2
│ ├── JSONSelect@0.4.0
│ ├── mustache@1.1.0
│ ├── object-path@0.8.1
│ ├─┬ transtype@1.0.0
│ │ └── dateable@1.0.1
│ └─┬ xml-mapping@1.7.0
│   ├── sax@0.4.2
│   └── xml-writer@1.6.0
├─┬ nconf@0.6.9
│ ├── async@0.2.9
│ ├── ini@1.3.3
│ └─┬ optimist@0.6.0
│   ├── minimist@0.0.10
│   └── wordwrap@0.0.2
├── object-path@0.6.0
├─┬ promised-mongo@0.11.1
│ ├─┬ mongodb@1.4.0
│ │ ├─┬ bson@0.2.7
│ │ │ └── nan@0.8.0
│ │ └── kerberos@0.0.3
│ ├── q@0.9.7
│ └─┬ readable-stream@1.1.13
│   ├── core-util-is@1.0.1
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
├── shorthash@0.0.2
```

**Comment by parmentf** [comment]
castorjs/castor-core@04cd56de2303251ca1ae24566aec0931930eacbb fixes the problem.
